# Generated by Django 3.1.4 on 2021-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subject_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=5500)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50, unique=True)),
                ('Day', models.CharField(max_length=50)),
                ('start_time_min', models.IntegerField()),
                ('end_time_min', models.IntegerField()),
            ],
        ),
    ]
