# Generated by Django 3.1.4 on 2021-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Subject',
            field=models.CharField(max_length=50),
        ),
    ]
